# Generated by Django 5.0.6 on 2024-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='meals/images/default.png', upload_to='meals/images'),
        ),
    ]
